services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "8443:81"
      - "443:443"
    depends_on:
      - martin
      - valhalla_shared
      - photon_shared
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt

  martin:
    image: ghcr.io/maplibre/martin:latest
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - ./martin/data:/files
    command: /files

  valhalla_shared:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    restart: unless-stopped
    expose:
      - "8002"
    volumes:
      - ./valhalla/shared:/custom_files
      - ./valhalla/valhalla.json:/custom_files/valhalla.json:ro

  photon_shared:
    image: rtuszik/photon-docker:latest
    restart: unless-stopped
    expose:
      - "2322"
    environment:
      - REGION=planet
      - UPDATE_INTERVAL=720h
    volumes:
      - ./photon/shared:/photon/data

volumes:
  npm_data:
  npm_letsencrypt:
